### ISSUE TITLE
"Poll intervall" is not minutes --> it is seconds

### ISSUE THREAD

**Issue by Seqway** [Scrounger/ioBroker.linux-control#12]
Hello,
your documentation says, that the Poll Intervall is given in minutes BUT i realised that the values are being polled in seconds when i put "1" in it --> i see it at the time stamp.
I tested it for the "My Commands" !

Please double check !

**Comment by Scrounger** [comment]
host poll interval is minutes
command poll interval is seconds.

doc updated and column description in adapter settings optimized.
