### ISSUE TITLE
Wenn ein Befehl kein Ergebnis zurückliefert steht im Datenpunkt  [sudo] password for user:

### ISSUE THREAD

**Issue by xCruziX** [Scrounger/ioBroker.linux-control#13]
**Describe the bug**  
Wenn ein Befehl aus dem Register "Meine Befehle" kein Ergebnis zurückliefert steht im Datenpunkt  "[sudo] password for user:"
wobei user der angemeldetet Benutzer ist.

**Expected behavior**  
Ich würde auch erwarten, dass der Datenpunkt dann nichts beinhaltet, also quasi einen leeren Text

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/59866158/98484526-70aae080-2210-11eb-8630-042922914ddc.png)
![image](https://user-images.githubusercontent.com/59866158/98484532-802a2980-2210-11eb-9641-06f628e8ee3e.png)

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 4.9.8
 - Node version: v12.19.0
 - Operating system: Ubuntu 20.04 LXC

**Comment by Scrounger** [comment]
Ich brauch bitte eine Bespiel für den Befehl wo so eine Rückgabe kommt

**Comment by xCruziX** [comment]
z.B. sudo -S echo ""
Ziemlich sinnfrei, aber scheinbar sobald ein leerer String als Egebnis zurückkommen würde.
Auch generell, wenn man einen Befehl einträgt, der einfach ausgeführt wird und kein Ergebnis liefert

**Comment by Scrounger** [comment]
https://github.com/Scrounger/ioBroker.linux-control/commit/5a64f61aa0dd4efddff79d1be1d896fb63652cb8
