### ISSUE TITLE
Js-Controller 3.2.x 

### ISSUE THREAD

**Issue by crunchip77** [Scrounger/ioBroker.linux-control#17]
Adapter version 1.1.2
mit dem Upgrade des Js-Controllers  kommen nun folgende Meldungen, nach einem update/upgrade einex LXC Containers

`

linux-control.0 | 2021-01-16 21:42:21.143 | warn | (4705) State "linux-control.0.motioneye.services.systemd-networkd.description" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
linux-control.0 | 2021-01-16 21:42:21.139 | warn | (4705) State "linux-control.0.motioneye.services.systemd-networkd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:21.130 | warn | (4705) State "linux-control.0.motioneye.services.systemd-networkd.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:21.117 | warn | (4705) State "linux-control.0.motioneye.services.systemd-networkd.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.789 | warn | (4705) State "linux-control.0.motioneye.services.NetworkManager.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.780 | warn | (4705) State "linux-control.0.motioneye.services.NetworkManager.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.773 | warn | (4705) State "linux-control.0.motioneye.services.NetworkManager.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.765 | warn | (4705) State "linux-control.0.motioneye.services.NetworkManager.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.709 | warn | (4705) State "linux-control.0.motioneye.services.man-db.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.704 | warn | (4705) State "linux-control.0.motioneye.services.man-db.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.699 | warn | (4705) State "linux-control.0.motioneye.services.man-db.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.692 | warn | (4705) State "linux-control.0.motioneye.services.man-db.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.686 | warn | (4705) State "linux-control.0.motioneye.services.logrotate.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.678 | warn | (4705) State "linux-control.0.motioneye.services.logrotate.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.673 | warn | (4705) State "linux-control.0.motioneye.services.logrotate.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.667 | warn | (4705) State "linux-control.0.motioneye.services.logrotate.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.647 | warn | (4705) State "linux-control.0.motioneye.services.ifupdown-pre.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.641 | warn | (4705) State "linux-control.0.motioneye.services.ifupdown-pre.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.635 | warn | (4705) State "linux-control.0.motioneye.services.ifupdown-pre.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.629 | warn | (4705) State "linux-control.0.motioneye.services.ifupdown-pre.load" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.499 | warn | (4705) State "linux-control.0.motioneye.services.connman.description" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.493 | warn | (4705) State "linux-control.0.motioneye.services.connman.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.489 | warn | (4705) State "linux-control.0.motioneye.services.connman.active" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-01-16 21:42:20.483 | warn | (4705) State "linux-control.0.motioneye.services.connman.load" has no existing object, this might lead to an error in future versions

`

**Comment by crunchip77** [comment]
Habe ich soeben gemacht, startete fehlerfrei

**Comment by Scrounger** [comment]
und meldungen sind weg?
