### ISSUE TITLE
"Meine Befehle" als ausführbarer Datenpunkt

### ISSUE THREAD

**Issue by MubiTec** [Scrounger/ioBroker.linux-control#19]
Hi,
Vielen Dank erstmal für die super guten Adapter.
Ich habe mir einen eigenen Befehl definiert. Dieser funktioniert auch wunderbar. 
Nun würde ich diesen aber nicht alle x Sekunden absetzen wollen, sondern durch ein externes Skript gesteuert. 
Ist das möglich? 
Danke schon mal!

**Comment by Scrounger** [comment]
![grafik](https://user-images.githubusercontent.com/6370451/111387277-c0f9e980-86ad-11eb-881d-239459f52f41.png)

dann wird vom Host das Polling interval genommen.
![grafik](https://user-images.githubusercontent.com/6370451/111387345-df5fe500-86ad-11eb-8212-2590e54f7134.png)

Wenn du nur Befehle senden willst (Button), dann erstell einen extra Host ohne Polling. Den Button kannst du per skript triggern.
