### ISSUE TITLE
Compatibility check to js-controller 3.3 and Admin5 React UI

### ISSUE THREAD

**Issue by ioBrokerChecker** [Scrounger/ioBroker.linux-control#21]
Dear Adapter developer,

with js-controller 3.2 and js-controller 3.3 some additional checks were added to make sure that created objects match to the specifications and also written state values match to the object definition.

If something is not correct this is logged as 'warning' or 'info' log.

Please take the time to verify your adapter by ideally starting with a fresh instance and do some actions and verify the log. If you see a warn log there from these checks please adjust the adapter and fix the relevant cases.

For questions please refer to https://github.com/ioBroker/ioBroker.js-controller/issues/1301 

Additionally we are preparing Admin 5 which will have a completely rewritten UI. Please install Admin 5, activate that new UI and verify that the configuration of you adapter works as expected also there.

More informations on Admin 5 can be found in Forum https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui 

Please close the issue after you checked it.

Thank you very much for your support!

**Comment by Flyor** [comment]
Seit dem Update auf JS 3.3 hab ich folgenden Fehler im Log: 
![image](https://user-images.githubusercontent.com/64526892/118184776-0df30580-b43c-11eb-86aa-30eaa0acdb08.png)

**Comment by Flyor** [comment]
Gibt's schon ne Lösung für das Problem, oder hat es mit dem JS Controller nix zu tun? Die Meldung hab ich seit dem Update

`



linux-control.0 | 2021-05-19 15:18:16.019 | warn | (1495) State "linux-control.0.iobroker.services.zfs-mount.description" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
linux-control.0 | 2021-05-19 15:18:16.014 | warn | (1495) State "linux-control.0.iobroker.services.zfs-mount.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-05-19 15:18:15.969 | warn | (1495) State "linux-control.0.iobroker.services.zfs-mount.active" has no existing object, this might lead to an error in future versions



`

@Scrounger

**Comment by Scrounger** [comment]
Alle Datenpunkte löschen und Adapter neu starten, sollte das Problem beheben

**Comment by Flyor** [comment]
> Alle Datenpunkte löschen und Adapter neu starten, sollte das Problem beheben

Ja und nein. Hab alle Objekte gelöscht, die Instanz und den Adapter neu installiert. Jetzt fehlen andere Objekte:

`



linux-control.0 | 2021-05-26 08:55:45.653 | warn | (2177661) State "linux-control.0.Grafana-Influx.services.fwupd.description" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
linux-control.0 | 2021-05-26 08:55:45.650 | warn | (2177661) State "linux-control.0.Grafana-Influx.services.fwupd.running" has no existing object, this might lead to an error in future versions
linux-control.0 | 2021-05-26 08:55:45.607 | warn | (2177661) State "linux-control.0.Grafana-Influx.services.fwupd.active" has no existing object, this might lead to an error in future versions



`

**Comment by Scrounger** [comment]
Done
