### ISSUE TITLE
Noobie Question: How do i get/generate the required RSA-Key?

### ISSUE THREAD

**Issue by bmueller77** [Scrounger/ioBroker.linux-control#24]
Hi, as i am just an IT-Pro using windows, i was asking myself, how to generate the RSA-Keyfile. Tried to put the R>egistry-Key, Putty generates into a file but i get the log entry in iobroker:

<html><body>

[getConnection]  error: Cannot parse privateKey: Unsupported key format, stack: Error:  Cannot parse privateKey: Unsupported key format     at Client.connect  (/opt/iobroker/node_modules/ssh2/lib/client.js:243:13)     at /opt/iobroker/node_modules/node-ssh/lib/cjs/index.js:193:24     at new Promise (<anonymous>)     at NodeSSH.connect  (/opt/iobroker/node_modules/node-ssh/lib/cjs/index.js:173:15)     at LinuxControl.getConnection  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:931:12)     at LinuxControl.refreshHost  (/opt/iobroker/node_modules/iobroker.linux-control/main.js:74:21)
--
linux-control.0 | 2021-09-01 01:43:00.729 | error | [getConnection] Could not establish a connection to 'OctoPrint' (192.168.xx.xx:22)!

</body>
</html>

Would be great, if you could add documentation, how to get/generate the keyfile. Thank you very much in advance.

**Comment by Scrounger** [comment]
There are a lot of how to's out there, example:
https://www.cyberciti.biz/faq/how-to-set-up-ssh-keys-on-linux-unix/
