### ISSUE TITLE
Falsche Objekttypen 

### ISSUE THREAD

**Issue by MMeinhardt1** [Scrounger/ioBroker.linux-control#27]
Hi,

bekomme folgende Meldungen im Log.

`2021-09-19 19:26:54.010 - info: linux-control.0 (26058) State value to set for "linux-control.0.ioBroker.info.is_online" has to be type "string" but received type "boolean"`

**Comment by Scrounger** [comment]
Bitte Datenpunkt löschen und adapter neu starten

**Comment by MMeinhardt1** [comment]
Erledigt, das Objekt wird allerdings nach Update bzw. Neustart wieder neu erstellt. 
Danke
