### ISSUE TITLE
Restart required do not go to false 

### ISSUE THREAD

**Issue by MubiTec** [Scrounger/ioBroker.linux-control#28]
The data point linux-control.0.Motion.needrestart.needrestart is always true, even if I just have restarted manually.
![Screenshot_2021-09-21-05-28-34-08](https://user-images.githubusercontent.com/44448393/134107359-ef5add36-4b1a-4b1c-8c49-c4187b4eb399.jpg)
Apapterversion 1.1.2
Restart package is installed 
May it is important: the host "motion" is not the host on which iobroker is running 
Plattform
    linux
Betriebssystem
    linux
Architektur
    x64
CPUs
    2
Geschwindigkeit
    3292 MHz
Modell
    Common KVM processor
RAM
    7.79 GB
System-Betriebszeit
    1 T. 05:20:21
Node.js
    v12.22.6
NPM
    6.14.15
Datenträgergröße
    10.81 GB
freier Festplattenspeicher
    5.47 GB
Anzahl der Adapter
    441
Betriebszeit
    1 T. 05:20:14
Aktive Instanzen
    28
location
    /opt/iobroker/
Hostname
    io

**Comment by Scrounger** [comment]
please provide the full debug log after adapter restart
