### ISSUE TITLE
Log error message

### ISSUE THREAD

**Issue by Draexl** [Scrounger/ioBroker.linux-control#30]
Was bedeutet diese Fehlermeldung bzw. was kann ich dagegen tun?
What does this error message mean? Or what can I do about it

`[cmdAptUpdate] SmartHomeDisplay1 (192.168.1.60:22): response error: E: Sperrdatei /var/lib/apt/lists/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung) E: Das Verzeichnis /var/lib/apt/lists/ kann nicht gesperrt werden. W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/pkgcache.bin - RemoveCaches (13: Keine Berechtigung) W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Keine Berechtigung), stack: ResponseError: [cmdAptUpdate] SmartHomeDisplay1 (192.168.1.60:22): E: Sperrdatei /var/lib/apt/lists/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung) E: Das Verzeichnis /var/lib/apt/lists/ kann nicht gesperrt werden. W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/pkgcache.bin - RemoveCaches (13: Keine Berechtigung) W: Problem beim Entfernen (unlink) der Datei /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Keine Berechtigung) at LinuxControl.sendCommand (/opt/iobroker/node_modules/iobroker.linux-control/main.js:872:26) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at LinuxControl.cmdAptUpdate (/opt/iobroker/node_modules/iobroker.linux-control/main.js:704:21) at LinuxControl.updateInfos (/opt/iobroker/node_modules/iobroker.linux-control/main.js:607:5) at LinuxControl.refreshHost (/opt/iobroker/node_modules/iobroker.linux-control/main.js:79:5)`

**Comment by Ajimaru** [comment]
Der Befehl apt update wurde nicht mit root rechten ausgeführt.
Das kannst du ändern in dem du diese Kontrolbox in den Adaptereinstellungen aktivierst.

![grafik](https://user-images.githubusercontent.com/38381946/147300560-00fd2e4f-4d35-496d-b9b4-57868fa78950.png)
