### ISSUE TITLE
warning im log

### ISSUE THREAD

**Issue by liv-in-sky** [Scrounger/ioBroker.linux-control#39]
habe dieses warning im log

`<html>
<body>

linux-control.0 | 2022-05-05 08:34:11.069 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
linux-control.0 | 2022-05-05 08:34:11.069 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
linux-control.0 | 2022-05-05 08:34:10.920 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-05-05 08:34:10.919 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
linux-control.0 | 2022-05-05 08:34:10.910 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-05-05 08:34:10.908 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"

</body>
</html>`

**Comment by Negalein** [comment]
bei mir auch

`Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"`

**Comment by mickym2** [comment]
Bei mir die gleichen Warnungen. Im Moment funktioniert aber noch alles.

<html>
<body>


linux-control.0 | 2022-07-30 13:20:42.265 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
linux-control.0 | 2022-07-30 13:20:42.263 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
linux-control.0 | 2022-07-30 13:20:42.092 | warn | This object will not be created in future versions. Please report this to the developer.
linux-control.0 | 2022-07-30 13:20:42.088 | warn | Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"


</body>
</html>

**Comment by Scrounger** [comment]
siehe #36

**Comment by rebel1985** [comment]
ich habe das selbe problem neustart und löschen des datenpunktes ohne erfolg

Object linux-control.0.command.host is invalid: obj.common.states has an invalid type! Expected "object", received "string"
