### ISSUE TITLE
warnung für version codename

### ISSUE THREAD

**Issue by liv-in-sky** [Scrounger/ioBroker.linux-control#4]
bekomme immer warnung 

inux-control.0 | 2020-08-11 07:53:13.395 | warn | (16322) [distributionInfo] IOBroker (192.168.178.59:22): property 'VERSION_CODENAME' not exist in result!
-- | -- | -- | --

brauchst du weitere infos über mein system ?

**Comment by Scrounger** [comment]
Welche Linux Dist?
Stell bitte den Adapter auf debug und poste das log. Am besten davor nur die distribution datenpunkte aktivieren, würde es für mich erleichtern.

**Comment by liv-in-sky** [comment]
kommt bei allen meinen proxmox containern

der proxmox ist 10 und die container sind 9

![Image 3](https://user-images.githubusercontent.com/18462890/89945802-39815f00-dc22-11ea-8878-f5f61fa99c61.png)

iobroker container

![Image 5](https://user-images.githubusercontent.com/18462890/89945961-76e5ec80-dc22-11ea-9460-7c005ffc5bfc.png)

**Comment by liv-in-sky** [comment]
und das log

![Image 6](https://user-images.githubusercontent.com/18462890/89946560-697d3200-dc23-11ea-9c57-964eaac2ab37.png)

**Comment by Scrounger** [comment]
ok ab debian 10 wird erst 'VERSION_CODENAME' mit geliefert. Das muss ich dann abfangen, damit da keine Warn meldung mehr kommt.

**Comment by Scrounger** [comment]
Um die Warnmeldung zu verhindern muss der Datenpunkt 'codename' auf die blacklist des entsprechnden Host gesetzt werden
