### ISSUE TITLE
Eigenen Intervall für Ordnerüberwachung

### ISSUE THREAD

**Issue by ipod86** [Scrounger/ioBroker.linux-control#40]
Hallo,

ist es möglich für die Ordnerüberwachung einen eigenen Abfrageibtervall zu integrieren?

Ich frage einige sehr große Ordner ab. Ich habe das Gefühl, dass das System dadurch sehr belastet wird.

**Comment by Scrounger** [comment]
Möglich schon, aber sehr aufwendig. Erstell dir doch einfach eine eigene manuell Abfrage, da kannst das Interval bereits festlegen. Und wenn der Ordner sehr groß ist, gibt es hier auch noch möglichkeiten das ganze zu optimieren per linux
