### ISSUE TITLE
Datapoints erweitern

### ISSUE THREAD

**Issue by Kuddel071089** [Scrounger/ioBroker.linux-control#41]
Aktuell nutze ich diesen Adapter um von allen VMs auf meinem ESX Host die CPU- und RAM-Auslastung sowie die Uptime abzufragen.
Dafür muss ich leider für jede VM jeweils drei manuelle Abfragen anlegen.

Könnte man diese Abfragen evtl. auf mit unter den vordefinierten Datapoints ansiedeln?

**Comment by Scrounger** [comment]
nein sorry das ist zu spezifisch. Je nach System / HW sind diese Befehle ggf. unterschiedlich.
