### ISSUE TITLE
Error with js-controller 5.x

### ISSUE THREAD

**Issue by Strobelix80** [Scrounger/ioBroker.linux-control#49]
**Describe the bug**  
Adapter is restarting with some errors:

Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

unhandled promise rejection: Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern

ReplyError: Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)

Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern

**To Reproduce**  
1. Just start the adapter instance

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version:  1.1.5
 - JS-Controller version: 5.0.3
 - Node version: v18.6.0
 - Operating system: Linux

**Comment by rotrichi** [comment]
Der iqontrol adapter wird nicht mehr grün 
<html>
<body>


17.06.2023 17:32:29.738 | warnen | Starten Sie den Adapter system.adapter.iqontrol.0 nicht neu, da eine Neustartschleife erkannt wurde
-- | -- | --
host.Ubuntu | 17.06.2023 17:32:29.738 | die Info | Starten Sie den Adapter system.adapter.iqontrol.0 neu, da er aktiviert ist
host.Ubuntu | 17.06.2023 17:32:29.738 | Fehler | Instanz system.adapter.iqontrol.0 mit Code 6 (UNCAUGHT_EXCEPTION) beendet
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Gefangen von Controller[1]: bei Iqontrol.emit (node:domain:475:12)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Gefangen von Controller[1]: bei Iqontrol.emit (node:events:527:28)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller erfasst[1]: bei Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller erfasst[1]: bei Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2253:16)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] erwischt: bei neuem Versprechen (<anonym>)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] abgefangen: unter /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2254:16
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3551:23)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Von Controller[1] abgefangen: bei Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Vom Controller[1] abgefangen: Fehler: Der Parameter „options“ muss ein echtes Objekt sein, aber der Typ „string“ wurde übergeben
host.Ubuntu | 17.06.2023 17:32:29.737 | Fehler | Von Controller[0] abgefangen: Dieser Fehler entstand entweder durch das Auslösen einer asynchronen Funktion ohne Catch-Block oder durch die Ablehnung eines Versprechens, das nicht mit .catch() behandelt wurde. Das Versprechen wurde mit der Begründung abgelehnt:
iqontrol.0 | 17.06.2023 17:32:29.696 | die Info | beendend
iqontrol.0 | 17.06.2023 17:32:29.196 | warnen | Beendet (UNCAUGHT_EXCEPTION): Ohne Grund
iqontrol.0 | 17.06.2023 17:32:29.196 | die Info | beendend
iqontrol.0 | 17.06.2023 17:32:29.196 | die Info | alles aufgeräumt...
iqontrol.0 | 17.06.2023 17:32:29.195 | die Info | Triggerintervalle stoppen...
iqontrol.0 | 17.06.2023 17:32:29.190 | Fehler | Der Parameter „options“ muss ein echtes Objekt sein, es wurde jedoch der Typ „string“ übergeben
iqontrol.0 | 17.06.2023 17:32:29.189 | Fehler | Fehler: Der Parameter „options“ muss ein echtes Objekt sein, aber der Typ „string“ wurde an Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts) übergeben :301:19) unter Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3551:23) unter /opt/iobroker/node_modules/@iobroker /js-controller-common/src/lib/common/tools.ts:2254:16 bei new Promise (<anonym>) bei Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src /lib/common/tools.ts:2253:16) bei Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25) bei Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker .iqontrol/main.js:413:14) bei Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14) bei Iqontrol.emit (node:events:527:28) bei Iqontrol.emit (node:domain:475:12)
iqontrol.0 | 17.06.2023 17:32:29.099 | Fehler | Unbehandelte Versprechensablehnung: Der Parameter „options“ muss ein echtes Objekt sein, aber der Typ „string“ wurde übergeben
iqontrol.0 | 17.06.2023 17:32:29.099 | Fehler | Unbehandelte Versprechensablehnung. Dieser Fehler entstand entweder durch das Einwerfen einer asynchronen Funktion ohne Catch-Block oder durch die Ablehnung eines Versprechens, das nicht mit .catch() behandelt wurde.
iqontrol.0 | 17.06.2023 17:32:29.090 | die Info | beginnend. Version 2.2.0 in /opt/iobroker/node_modules/iobroker.iqontrol, Knoten: v16.16.0, js-controller: 5.0.4
host.Ubuntu | 17.06.2023 17:32:28.675 | die Info | Instanz system.adapter.iqontrol.0 wurde mit der PID 3231266 gestartet
host.Ubuntu | 17.06.2023 17:32:25.390 | die Info | Starten Sie den Adapter system.adapter.iqontrol.0 neu, da er aktiviert ist
host.Ubuntu | 17.06.2023 17:32:25.390 | Fehler | Instanz system.adapter.iqontrol.0 mit Code 6 (UNCAUGHT_EXCEPTION) beendet
host.Ubuntu | 17.06.2023 17:32:25.390 | Fehler | Gefangen von Controller[1]: bei Iqontrol.emit (node:domain:475:12)
host.Ubuntu | 17.06.2023 17:32:25.390 | Fehler | Gefangen von Controller[1]: bei Iqontrol.emit (node:events:527:28)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller erfasst[1]: bei Iqontrol.onReady (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1779:14)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller erfasst[1]: bei Iqontrol.createInfoConnection (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:413:14)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.createOrUpdateObject (/opt/iobroker/node_modules/iobroker.iqontrol/main.js:1673:25)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.getObjectAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2253:16)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] erwischt: bei neuem Versprechen (<anonym>)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] abgefangen: unter /opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2254:16
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] abgefangen: bei Iqontrol.getObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:3551:23)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Von Controller[1] abgefangen: bei Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Vom Controller[1] abgefangen: Fehler: Der Parameter „options“ muss ein echtes Objekt sein, aber der Typ „string“ wurde übergeben
host.Ubuntu | 17.06.2023 17:32:25.389 | Fehler | Von Controller[0] abgefangen: Dieser Fehler entstand entweder durch das Auslösen einer asynchronen Funktion ohne Catch-Block oder durch die Ablehnung eines Versprechens, das nicht mit .catch() behandelt wurde. Das Versprechen wurde mit der Begründung abgelehnt:
iqontrol.0 | 2023-06-17 17:32:25.345 | die Info | beendend
iqontrol.0 | 17.06.2023 17:32:24.845 | warnen | Beendet (UNCAUGHT_EXCEPTION): Ohne Grund
iqontrol.0 | 17.06.2023 17:32:24.845 | die Info | beendend
iqontrol.0 | 17.06.2023 17:32:24.845 | die Info | alles aufgeräumt...
iqontrol.0 | 17.06.2023 17:32:24.845 | die Info | Triggerintervalle stoppen...


</body>
</html>

**Comment by Strobelix80** [comment]
> **Describe the bug** Adapter is restarting with some errors:
> 
> Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 
> unhandled promise rejection: Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern
> 
> ReplyError: Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12) at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
> 
> Error The pattern "linux-control.0.Heizung.services.●.restart" is not a valid ID pattern
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Just start the adapter instance
> 
> **Screenshots & Logfiles** If applicable, add screenshots and logfiles to help explain your problem.
> 
> **Versions:**
> 
> * Adapter version:  1.1.5
> * JS-Controller version: 5.0.3
> * Node version: v18.6.0
> * Operating system: Linux

Filtering with whitelist fixes the error

**Comment by Negalein** [comment]
> Filtering with whitelist fixes the error

Hallo

Wie/nach was hast du gefiltert?
Danke
