### ISSUE TITLE
bedienung des adapter settings

### ISSUE THREAD

**Issue by liv-in-sky** [Scrounger/ioBroker.linux-control#5]
ich habe 8 server im setting eingetragen - wenn ich nun unter dem tab DATENPUNKTE versuche, z.b den restart datenpunkt auszuschließen (damit er nicht angezeigt wird) bei dem server, der ganz unten angezeigt wird, ist das nicht möglich

wenn ich runter scrolle, um den letzten server zu sehen, verschwinden auf der linken seite die datenpunkte - kann somit nix auswählen

![Image 1](https://user-images.githubusercontent.com/18462890/89862876-1e263d80-dba9-11ea-8cfb-453bd4b379b1.png)

**Comment by Scrounger** [comment]
Welchen Browser verwendest du? Kann das mit firefox & chrome nicht reproduzieren

**Comment by liv-in-sky** [comment]
hier mal ein filmchen - ist chrome

wenn ich den server runter scrolle zum letzten - dann kann ich von oben nichts mehr reinziehen - oder wenn ich oben einen dp nehme komme ich nicht runter zum letzten server

![smart61](https://user-images.githubusercontent.com/18462890/89945035-07bbc880-dc21-11ea-9607-4a1424ce6ca6.gif)

**Comment by liv-in-sky** [comment]
habe es eben mit FF ausprobiert - da geht es

**Comment by liv-in-sky** [comment]
ich weiß nicht ob das hilft

![Image 1](https://user-images.githubusercontent.com/18462890/89945321-76992180-dc21-11ea-8556-8c74779021c2.png)

**Comment by Scrounger** [comment]
Also bei mir geht das auch mit Chrome 84.x (Windows), man muss bloß viel besser zielen.
Die Meldung sagt mir leider nix. Welche Chrome Version hast du?

![chrome](https://user-images.githubusercontent.com/6370451/89945758-266e8f00-dc22-11ea-909f-68c5eeb4c4e2.gif)

**Comment by liv-in-sky** [comment]
version neuste - 84...

habe mal das chrome fenster verkleinert - jetzt hat es geklappt

habe nochmal "fest" gezogen :-)
bei fullscreen des browsers gibt es genau unten rechts eine stelle, da funktioniert es  - zwar nicht besonders gut - aber soweit klappt es - ich denke , dass kannst du schliessen hier
