### ISSUE TITLE
commands in eigenen datenpunkt ordner

### ISSUE THREAD

**Issue by liv-in-sky** [Scrounger/ioBroker.linux-control#9]
ich hoffe, ich nerve nicht zu viel

wäre es möglich die commands auch in einen eigenen dp-ordner zu speichern ?

**Comment by Scrounger** [comment]
Das geht schon du musst als ID dann halt meinOrdner.meinDatenpunkt zb schreiben

**Comment by liv-in-sky** [comment]
danke - doch so einfach - aber ich lasse es so wie es ist - sonst muss ich das für mein script auch noch erklären - such einfach nach datenpunkten mit der role botton
